services:
  web:
    build: .
    ports:
      - "5123:8080"
    environment:
      #MqttHost: mqtt
      MqttHost: 192.168.0.114
      Npsql__Connectionstring: Host=db:5432;Username=postgres;Password=example;Database=postgres
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: example
  mqtt: # still needs config to allow anonymous
    image: eclipse-mosquitto